apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hospital-net-ca
  namespace: hospital-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: hospital-net-ca
  chart:
    git: ssh://git@github.com/bfsmaksym/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: hospital-net
      images:
        alpineutils: index.docker.io/wmcgroup777/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: hospital-admin
    storage:
      storageclassname: hospitalsc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: https://vault.bfs-network.name:8200
      authpath: hospital-net-auth
      secretcert: secret_hospital/crypto/peerOrganizations/hospital-net/ca?ca.hospital-net-cert.pem
      secretkey: secret_hospital/crypto/peerOrganizations/hospital-net/ca?hospital-net-CA.key
      secretadminpass: secret_hospital/credentials/hospital-net/ca/hospital?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: peer
